// data.js
export const ingredient_prices = [
    {ingredient: "apple", price: 1},
    {ingredient: "apples", price: 1},
    {ingredient: "blackberries", price: 1},
    {ingredient: "apple cider", price: 2},
    {ingredient: "simple syrup", price: 1},
    {ingredient: "lemon juice", price: 1},
    {ingredient: "bourbon", price: 3},
    {ingredient: "cinnamon sugar", price: 1},
    {ingredient: "club soda", price: 1},
    {ingredient: "apple juice", price: 1},
    {ingredient: "angostura bitters", price: 3},
    {ingredient: "vodka", price: 3},
    {ingredient: "green apple", price: 1},
    {ingredient: "oats", price: 1},
    {ingredient: "blueberries", price: 1},
    {ingredient: "liqueur", price: 2},
    {ingredient: "sparkling wine", price: 3},
    {ingredient: "orange twist", price: 2},
    {ingredient: "berries", price: 1},
    {ingredient: "cloves", price: 1},
    {ingredient: "black peppercorns", price: 1},
    {ingredient: "brandy", price: 4},
    {ingredient: "syrup", price: 1},
    {ingredient: "cinnamon sticks", price: 2},
    {ingredient: "cider", price: 2},
    {ingredient: "fuji", price: 1},
    {ingredient: "tart apples", price: 1},
    {ingredient: "kosher salt", price: 1},
    {ingredient: "apple cider vinegar", price: 1},
    {ingredient: "fennel seeds", price: 1},
    {ingredient: "granulated sugar", price: 1},
    {ingredient: "cinnamon sugar", price: 1},
    {ingredient: "cinnamon stick", price: 1},
    {ingredient: "sherry", price: 4},
    {ingredient: "ground cinnamon", price: 1},
]
