// data.js
export const ingredient_prices = [
    {ingredient: "apple", price: 1},
    {ingredient: "apples", price: 1},
    {ingredient: "blackberries", price: 1},
    {ingredient: "apple cider", price: 2},
    {ingredient: "simple syrup", price: 1},
    {ingredient: "lemon juice", price: 1},
    {ingredient: "bourbon", price: 3},
    {ingredient: "cinnamon sugar", price: 1},
    {ingredient: "club soda", price: 1},
    {ingredient: "apple juice", price: 1},
    {ingredient: "angostura bitters", price: 3},
    {ingredient: "vodka", price: 3},
    {ingredient: "green apple", price: 1},
    {ingredient: "oats", price: 1},
    {ingredient: "blueberries", price: 1},
    {ingredient: "liqueur", price: 2},
    {ingredient: "sparkling wine", price: 3},
    {ingredient: "orange twist", price: 2},
    {ingredient: "berries", price: 1},
    {ingredient: "cloves", price: 1},
    {ingredient: "black peppercorns", price: 1},
    {ingredient: "brandy", price: 4},
    {ingredient: "syrup", price: 1},
    {ingredient: "cinnamon sticks", price: 2},
    {ingredient: "cider", price: 2},
    {ingredient: "fuji", price: 1},
    {ingredient: "tart apples", price: 1},
    {ingredient: "kosher salt", price: 1},
    {ingredient: "apple cider vinegar", price: 1},
    {ingredient: "fennel seeds", price: 1},
    {ingredient: "granulated sugar", price: 1},
    {ingredient: "cinnamon sugar", price: 1},
    {ingredient: "cinnamon stick", price: 1},
    {ingredient: "sherry", price: 4},
    {ingredient: "ground cinnamon", price: 1},
    {ingredient: "whiskey", price: 3},
    {ingredient: "sugar", price: 1},
    {ingredient: "egg white", price: 1},
    {ingredient: "milk", price: 1},
    {ingredient: "powdered sugar", price: 1},
    {ingredient: "black pepper", price: 1},
    {ingredient: "saffron", price: 2},
    {ingredient: "unsalted butter", price: 1},
    {ingredient: "eggs", price: 1},
    {ingredient: "all-purpose flour", price: 1},
    {ingredient: "salt", price: 1},
    {ingredient: "tequila", price: 4},
    {ingredient: "triple sec", price: 2},
    {ingredient: "lime juice", price: 1},
    {ingredient: "salt", price: 1},
    {ingredient: "turnips", price: 1},
    {ingredient: "garlic", price: 1},
    {ingredient: "cream", price: 1},
    {ingredient: "pepper", price: 1},
    {ingredient: "cantaloupe", price: 1},
    {ingredient: "lime", price: 1},
    {ingredient: "sauvignon blanc", price: 3},
    {ingredient: "mint", price: 1},
    {ingredient: "dry vermouth", price: 2},
    {ingredient: "green grapes", price: 1},
    {ingredient: "bartlett pear", price: 1},
    {ingredient: "raspberries", price: 1},
    {ingredient: "nectarine", price: 1},
    {ingredient: "cinammon", price: 1},
    {ingredient: "lemon", price: 1},
    {ingredient: "gin", price: 3},
    {ingredient: "asparagus", price: 1},
    {ingredient: "mustard", price: 1},
    {ingredient: "gruyere", price: 2},
    {ingredient: "bird chiles", price: 2},
    {ingredient: "white peppercorns", price: 2},
    {ingredient: "fresh orange juice", price: 2},
    {ingredient: "maple syrup", price: 2},
    {ingredient: "peanut butter", price: 1},
    {ingredient: "strawberry yogurt", price: 2},
    {ingredient: "pecans", price: 2},
    {ingredient: "butter", price: 1},
    {ingredient: "lillet", price: 4},
    {ingredient: "bitters", price: 2},
    {ingredient: "lemon twist", price: 1},
    {ingredient: "jalapeño", price: 2},
    {ingredient: "aperol", price: 3},
    {ingredient: "ipa", price: 2},
    {ingredient: "foie gras", price: 5},
    {ingredient: "oranges", price: 1},
    {ingredient: "grapefruit", price: 1},
    {ingredient: "cranberries", price: 1},
    {ingredient: "honey", price: 1},
    {ingredient: "semisweet chocolate", price: 1},
    {ingredient: "heavy cream", price: 1},
    {ingredient: "egg yolks", price: 1},
    {ingredient: "egg whites", price: 1},
    {ingredient: "vanilla extract", price: 2},
    {ingredient: "cinnamon bread", price: 2},
    {ingredient: "coffee", price: 2},
    {ingredient: "superfine sugar", price: 2},
    {ingredient: "orange flower water", price: 2},
    {ingredient: "flour", price: 1},
    {ingredient: "confectioner sugar", price: 1},
    {ingredient: "bitterseet chocolate", price: 2},
    {ingredient: "chicken livers", price: 1},
    {ingredient: "shallots", price: 1},
    {ingredient: "cognac", price: 3},
    {ingredient: "allspice", price: 1},
    {ingredient: "fresh thyme", price: 1},
    {ingredient: "water", price: 0},
    {ingredient: "gelatin", price: 1},
    {ingredient: "cherries", price: 1},
    {ingredient: "baking powder", price: 1},
    {ingredient: "confectioner", price: 1},
    {ingredient: "dark brown sugar", price: 2},
    {ingredient: "egg", price: 1},
    {ingredient: "unsweetened chocolate", price: 2},
    {ingredient: "semisweet chocolate", price: 2},
    {ingredient: "mandarin oranges", price: 1},
    {ingredient: "bread flour", price: 1},
    {ingredient: "baking soda", price: 1},
    {ingredient: "whole milk", price: 1},
    {ingredient: "cheddar cheese", price: 1},
    {ingredient: "salted peanuts", price: 1},
    {ingredient: "seltzer", price: 2},
    {ingredient: "egg yolk", price: 1},
    {ingredient: "bittersweet chocolate", price: 1},
    {ingredient: "parsley", price: 1},
    {ingredient: "shallot", price: 1},
    {ingredient: "table salt", price: 1},
    {ingredient: "shrimp", price: 2},
    {ingredient: "ground pepper", price: 1},
    {ingredient: "potatoes", price: 1},
    {ingredient: "chives", price: 1},
    {ingredient: "scallops", price: 1},
    {ingredient: "white pepper", price: 1},
    {ingredient: "canola oil", price: 1},
    {ingredient: "spinach", price: 1},
    {ingredient: "shiitake mushrooms", price: 2},
    {ingredient: "olive oil", price: 1},
    {ingredient: "piment d espelette", price: 4},
    {ingredient: "soybean oil", price: 1},
    {ingredient: "oregano", price: 1},
    {ingredient: "thyme", price: 1},
    {ingredient: "piment d' espellete", price: 4},
    {ingredient: "beans", price: 1},
    {ingredient: "molasses", price: 1},
    {ingredient: "brown sugar", price: 2},
    {ingredient: "ground cloves", price: 1},
    {ingredient: "bacon", price: 1},
    {ingredient: "onion", price: 1},
    {ingredient: "parmesan cheese", price: 1},
    {ingredient: "herbs", price: 1},
    {ingredient: "bread crumbs", price: 1},
    {ingredient: "ground beef", price: 2},
    {ingredient: "sausage", price: 2},
    {ingredient: "olive oil", price: 1},
    {ingredient: "marinara sauce", price: 2},
    {ingredient: "chicken broth", price: 1},
    {ingredient: "hoagie rolls", price: 1},
    {ingredient: "mozzarella cheese", price: 1},
    {ingredient: "parsley", price: 1},
    {ingredient: "sea salt", price: 1},
    {ingredient: "creme fraiche", price: 2},
    {ingredient: "apricots", price: 1},
    {ingredient: "light brown sugar", price: 1},
    {ingredient: "buttermilk", price: 1},
    {ingredient: "self rising flour", price: 1},
    {ingredient: "oatmeal", price: 1},
    {ingredient: "cinnamon", price: 1},
    {ingredient: "plums", price: 1},
    {ingredient: "squid", price: 3},
    {ingredient: "thyme", price: 1},
    {ingredient: "lemon zest", price: 1},
    {ingredient: "cucumbers", price: 1},
    {ingredient: "black olives", price: 1},
    {ingredient: "orange", price: 1},
    {ingredient: "punt e mes", price: 4},
    {ingredient: "arugula", price: 1},
    {ingredient: "pecorino", price: 3},
    {ingredient: "strawberries", price: 1},
    {ingredient: "champagne", price: 3},
    {ingredient: "peppercorns", price: 1},
    {ingredient: "egg pasta", price: 1},
    {ingredient: "pecorino cheese", price: 3},
    {ingredient: "pasta", price: 1},
    {ingredient: "hard boiled eggs", price: 1},
    {ingredient: "capsicum", price: 1},
    {ingredient: "sweet corn", price: 1},
    {ingredient: "masala", price: 2},
    {ingredient: "dried parsley", price: 1},
    {ingredient: "chili", price: 1},
    {ingredient: "white vinegar", price: 1},
    {ingredient: "extra virgin olive oil", price: 1},
    {ingredient: "rye whiskey", price: 4},
    {ingredient: "maraschino liqueur", price: 5},
    {ingredient: "campari", price: 4},
    {ingredient: "sweet vermouth", price: 2},
    {ingredient: "bucatini", price: 1},
    {ingredient: "pecorino", price: 3},
    {ingredient: "piment d' espelette", price: 3},
    {ingredient: "yeast", price: 1},
    {ingredient: "all purpose flour", price: 1},
    {ingredient: "pistachio", price: 1},
    {ingredient: "pastry flour", price: 1},
    {ingredient: "vanilla bean", price: 1},
    {ingredient: "extra-virgin olive oil", price: 1},
    {ingredient: "fleur de sel", price: 2},
    {ingredient: "milk powder", price: 2},
    {ingredient: "fine sea salt", price: 1},
    {ingredient: "barley malt syrup", price: 3},
    {ingredient: "fresh rosemary", price: 1},
    {ingredient: "coarse salt", price: 1},
    {ingredient: "kalamata olives", price: 1},
    {ingredient: "ice", price: 1},
    {ingredient: "ground coffee", price: 2},
    {ingredient: "confectioners", price: 1},
    {ingredient: "almond flour", price: 2},
    {ingredient: "mayonnaise", price: 1},
    {ingredient: "anchovy fillets", price: 1},
    {ingredient: "red wine vinegar", price: 1},
    {ingredient: "hot sauce", price: 1},
    {ingredient: "romaine", price: 1},
    {ingredient: "sourdough", price: 2},
    {ingredient: "sesame seeds", price: 1},
    {ingredient: "malt syrup", price: 1},
    {ingredient: "semolina flour", price: 2},
    {ingredient: "almonds", price: 1},
    {ingredient: "food coloring", price: 1},
    {ingredient: "cornichons", price: 1},
    {ingredient: "ketchup", price: 1},
    {ingredient: "hot sauce", price: 1},
    {ingredient: "raisins", price: 1},
    {ingredient: "cocoa", price: 1},
    {ingredient: "dried apricots", price: 1},
    {ingredient: "dried pears", price: 1},
    {ingredient: "dried peaches", price: 1},
    {ingredient: "dried prunes", price: 1},
    {ingredient: "walnuts", price: 1},
    {ingredient: "dark rum", price: 4},
    {ingredient: "cucumber", price: 1},
    {ingredient: "tonic", price: 1},
    {ingredient: "leaven", price: 3},
    {ingredient: "spelt flour", price: 2},
    {ingredient: "cardamom", price: 2},
    {ingredient: "rolled oats", price: 1},
    {ingredient: "sunflower seeds", price: 1},
    {ingredient: "pumpkin seeds", price: 1},
    {ingredient: "coconut", price: 1},
    {ingredient: "dates", price: 2},
    {ingredient: "sour cherries", price: 1},
    {ingredient: "sorghum flour", price: 2},
    {ingredient: "rice flour", price: 2},
    {ingredient: "cornmeal", price: 1},
    {ingredient: "potato starch", price: 1},
    {ingredient: "xanthan gum", price: 3},
    {ingredient: "ener-g egg replacer", price: 2},
    {ingredient: "pitted prunes", price: 1},
    {ingredient: "madeira", price: 3},
    {ingredient: "grated nutmeg", price: 1},
    {ingredient: "beef broth", price: 1},
    {ingredient: "beef", price: 2},
    {ingredient: "ramen", price: 1},
    {ingredient: "been sprouts", price: 1},
    {ingredient: "jalapeno", price: 1},
    {ingredient: "fresh basil", price: 1},
    {ingredient: "shitake mushrooms", price: 1},
    {ingredient: "scallions", price: 1},
    {ingredient: "chili powder", price: 1},
    {ingredient: "fresh ginger", price: 1},
    {ingredient: "cumin", price: 1},
    {ingredient: "sriracha", price: 1},
    {ingredient: "chicken", price: 1},
    {ingredient: "bran cereal", price: 1},
    {ingredient: "potato crisps", price: 1},
    {ingredient: "onion powder", price: 1},
    {ingredient: "garlic powder", price: 1},
    {ingredient: "cayenne pepper", price: 1},    
    {ingredient: "chicken breast", price: 1},
    {ingredient: "pepper sauce", price: 1},
    {ingredient: "cooking spray", price: 1},
    {ingredient: "rolls", price: 1},
    {ingredient: "chiles", price: 1},
    {ingredient: "cheese", price: 1},
    {ingredient: "red bell pepper", price: 1},
    {ingredient: "cashew nuts", price: 1},
    {ingredient: "turmeric", price: 1},
    {ingredient: "ghee", price: 2},
    {ingredient: "piece ginger", price: 1},
    {ingredient: "lemongrass", price: 1},
    {ingredient: "green chilies", price: 1},
    {ingredient: "curry leaves", price: 1},
    {ingredient: "coriander", price: 1},
    {ingredient: "coconut milk", price: 2},
    {ingredient: "boneless, skinless chicken breast", price: 1},
    {ingredient: "wheat noodles", price: 1},
    {ingredient: "dark sesame oil", price: 1},
    {ingredient: "sesame", price: 1},
    {ingredient: "soy sauce", price: 1},
    {ingredient: "cane sugar", price: 1},
    {ingredient: "rice vinegar", price: 1},
    {ingredient: "mirin", price: 1},
    {ingredient: "oil", price: 1},
    {ingredient: "english cucumber", price: 1},
    {ingredient: "green onions", price: 1},
    {ingredient: "galliano", price: 5},
    {ingredient: "chartreuse", price: 6},
    {ingredient: "demerara sugar", price: 2},
    {ingredient: "cane sugar", price: 1},
    {ingredient: "panko", price: 1},
    {ingredient: "za'atar", price: 2},
    {ingredient: "cheese", price: 1},
    {ingredient: "vegetable oil", price: 1},
    {ingredient: "dijon mustard", price: 1},
    {ingredient: "salad greens", price: 1},
    {ingredient: "cherry tomatoes", price: 1},
    {ingredient: "pork shoulder", price: 2},
    {ingredient: "catsup", price: 1},
    {ingredient: "avocado", price: 1},
    {ingredient: "banana", price: 1},
    {ingredient: "orange juice", price: 1},
    {ingredient: "mint tea", price: 1},
    {ingredient: "sugar snap peas", price: 1},
    {ingredient: "shortening", price: 2},
    {ingredient: "ice water", price: 1},
    {ingredient: "potato starch", price: 1},
    {ingredient: "sweet cherries", price: 1},
    {ingredient: "lamb mince", price: 3},
    {ingredient: "pine nuts", price: 1},
    {ingredient: "pomegranate molasses", price: 2},
    {ingredient: "all spice", price: 1},
    {ingredient: "plum tomatoes", price: 1},
    {ingredient: "toasted sesame oil", price: 1},
    {ingredient: "chicken bouillon", price: 1},
    {ingredient: "green onion", price: 1},
    {ingredient: "steamed jasmine rice", price: 1},
    {ingredient: "espresso", price: 1},
    {ingredient: "chipotle chiles", price: 1},
    {ingredient: "guajillo chiles", price: 1},
    {ingredient: "habenero chile", price: 1},
    {ingredient: "peanuts", price: 1},
    {ingredient: "hulled pumpkin seeds", price: 1},
    {ingredient: "pizza dough", price: 1},
    {ingredient: "mozzarella", price: 1},
    {ingredient: "soft goat cheese", price: 1},
    {ingredient: "parmesan", price: 1},
    {ingredient: "dried oregano", price: 1},
    {ingredient: "habanero chile", price: 1},
    {ingredient: "sandwich bread", price: 1},
    {ingredient: "jelly", price: 1},
    {ingredient: "grenadine", price: 2},
    {ingredient: "almond milk", price: 1},
    {ingredient: "waffle mix", price: 1},
    {ingredient: "sugarcane", price: 1},
    {ingredient: "rum", price: 4},
    {ingredient: "white rum", price: 4},
    {ingredient: "ginger", price: 1},
    {ingredient: "scotch", price: 4},
    {ingredient: "coffee beans", price: 1},
    {ingredient: "orange peel", price: 1},
    {ingredient: "unsweetened almond milk", price: 1},
    {ingredient: "whole-milk greek yogurt", price: 1},
    {ingredient: "chia seeds", price: 2},
    {ingredient: "strawberry jam", price: 1},
    {ingredient: "wheat bread", price: 1},
    {ingredient: "jelly", price: 1},
    {ingredient: "cucumber juice", price: 1},
    {ingredient: "jam", price: 1},
    {ingredient: "light corn syrup", price: 1},
    {ingredient: "special k cereal", price: 1},
    {ingredient: "semisweet chocolate chips", price: 1},
    {ingredient: "ginger root", price: 1},
    {ingredient: "soda water", price: 1},
    {ingredient: "porterhouse steak", price: 4},
    {ingredient: "seasoning", price: 1},
    {ingredient: "leeks", price: 1},
    {ingredient: "russet potatoes", price: 1},
    {ingredient: "button mushrooms", price: 2},
    {ingredient: "white wine vinegar", price: 1},
    {ingredient: "rosemary", price: 1},
    {ingredient: "red pepper flakes", price: 1},
    {ingredient: "donut", price: 1},
    {ingredient: "sweetened condensed milk", price: 1},
    {ingredient: "roma tomatoes", price: 1},
    {ingredient: "red onion", price: 1},
    {ingredient: "tomato paste", price: 2},
    {ingredient: "chile", price: 1},
    {ingredient: "corn flakes", price: 1},
    {ingredient: "vanilla", price: 1},
    {ingredient: "yukon gold potatoes", price: 1},
    {ingredient: "season", price: 1},
    {ingredient: "plain whole milk yogurt", price: 1},
    {ingredient: "plantains", price: 2},
    {ingredient: "condensed milk", price: 1},
    {ingredient: "hibiscus flowers", price: 1},
    {ingredient: "filtered water", price: 1},
    {ingredient: "black tea", price: 1},
    {ingredient: "sweet potato", price: 1},
    {ingredient: "olive", price: 1},
    {ingredient: "ricotta", price: 1},
    {ingredient: "egg (yolk", price: 1},
    {ingredient: "muffin", price: 2},
    {ingredient: "tonic water", price: 1},
    {ingredient: "sprite", price: 1},
    {ingredient: "grape", price: 1},
    {ingredient: "wheat germ", price: 2},
    {ingredient: "coffee liqueur", price: 3},
    {ingredient: "marsala", price: 2},
    {ingredient: "mascarpone", price: 2},
    {ingredient: "ladyfingers", price: 1},
    {ingredient: "dark chocolate", price: 1},
    {ingredient: "unsweetened cocoa powder", price: 1},
    {ingredient: "frozen rasberries", price: 1},
    {ingredient: "carrots", price: 1},
    {ingredient: "bartlett pears", price: 1},
    {ingredient: "pears", price: 1},
    {ingredient: "kefir", price: 2},
    {ingredient: "celery", price: 1},
    {ingredient: "granny smith apple", price: 1},
    {ingredient: "butternut squash", price: 1},
    {ingredient: "low sodium chicken stock", price: 1},
    {ingredient: "oreo", price: 1},
    {ingredient: "ice cream", price: 2},
    {ingredient: "ginger beer", price: 2},
    {ingredient: "half-and-half", price: 1},
    {ingredient: "canned black beans", price: 1},
    {ingredient: "flour tortillas", price: 1},
    {ingredient: "salsa", price: 1},
    {ingredient: "sour cream", price: 1},
    {ingredient: "roast of beef", price: 4},
    {ingredient: "squash", price: 1},
    {ingredient: "rotini", price: 1},
    {ingredient: "yellow onion", price: 1},
    {ingredient: "cream cheese", price: 1},
    {ingredient: "vegetable broth", price: 1},
    {ingredient: "white cheddar cheese", price: 1},
    {ingredient: "salted butter", price: 1},
    {ingredient: "chocolate chips", price: 1},
    {ingredient: "confectioners sugar", price: 1},
    {ingredient: "sandwich cookies", price: 1},
    {ingredient: "top round steak", price: 3},
    {ingredient: "sweet onion", price: 1},
    {ingredient: "bell peppers", price: 1},
    {ingredient: "provolone cheese", price: 1},
    {ingredient: "jell-o", price: 1},
    {ingredient: "rhubarb", price: 1},
    {ingredient: "raspberry jell-o", price: 1},
    {ingredient: "whipped topping", price: 1},
    {ingredient: "fresh blueberries", price: 1},
    {ingredient: "lime jell-o", price: 1},
    {ingredient: "pineapple", price: 1},
    {ingredient: "cool whip", price: 1},
    {ingredient: "rice paper", price: 1},
    {ingredient: "malt-o-meal", price: 2},
    {ingredient: "coconut flakes", price: 2},
    {ingredient: "hot chili sauce", price: 1},
    {ingredient: "heavy whipping cream", price: 1},
    {ingredient: "orange jell-o", price: 1},
    {ingredient: "pumpkin", price: 1},
    {ingredient: "peach", price: 1},
    {ingredient: "1% milk", price: 1},
    {ingredient: "cooked chickpeas", price: 1},
    {ingredient: "agave nectar", price: 2},
    {ingredient: "whole wheat flour", price: 1},
    {ingredient: "fine grain sea salt", price: 1},
    {ingredient: "poppy seeds", price: 1},
    {ingredient: "eggplants", price: 1},
    {ingredient: "ricotta cheese", price: 1},
    {ingredient: "prosciutto", price: 2},
    {ingredient: "tomato sauce", price: 1},
    {ingredient: "italian bread", price: 1},
    {ingredient: "zucchini", price: 1},
    {ingredient: "breadcrumbs", price: 1},
    {ingredient: "worcestershire sauce", price: 2},
    {ingredient: "cornstarch", price: 1},
    {ingredient: "oysters", price: 3},
    {ingredient: "beer", price: 2},
    {ingredient: "rye flour", price: 1},
    {ingredient: "mustard powder", price: 2},
    {ingredient: "paprika", price: 1},
    {ingredient: "cheddar", price: 1},
    {ingredient: "chicken parts", price: 1},
    {ingredient: "carrot", price: 1},
    {ingredient: "leek", price: 1},
    {ingredient: "bouquet garni", price: 2},
    {ingredient: "lemon-lime soda", price: 1},
    {ingredient: "cherry", price: 1},
    {ingredient: "fresh herbs", price: 1},
    {ingredient: "peas", price: 1},
    {ingredient: "spring onion", price: 1},
    {ingredient: "vegetable", price: 1},
    {ingredient: "mint leaves", price: 1},
    {ingredient: "cordial", price: 2},
    {ingredient: "evaporated milk", price: 1},
    {ingredient: "cream of coconut", price: 1},
    {ingredient: "unsweetened coconut milk", price: 1},
    {ingredient: "star anise", price: 1},
    {ingredient: "ground pork", price: 2},
    {ingredient: "soybean", price: 1},
    {ingredient: "pâté", price: 2},
    {ingredient: "fish sauce", price: 1},
    {ingredient: "pork", price: 3},
    {ingredient: "ground pork", price: 2},
    {ingredient: "pork skin", price: 2},
    {ingredient: "papaya", price: 1},
    {ingredient: "rice vermicelli noodles", price: 1},
    {ingredient: "persian cucumbers", price: 1},
    {ingredient: "mango", price: 1},
    {ingredient: "prepared horseradish", price: 1},
    {ingredient: "nilla wafers", price: 2},
    {ingredient: "jelly beans", price: 1},
    {ingredient: "licorice", price: 1},
    {ingredient: "prawns", price: 3},
    {ingredient: "green chili", price: 1},
    {ingredient: "cooking oil", price: 1},
    {ingredient: "vinegar", price: 1},
    {ingredient: "black beans", price: 1},
    {ingredient: "italian sausage", price: 2},
    {ingredient: "kielbasa", price: 2},
    {ingredient: "ham hock", price: 2},
    {ingredient: "bay leaves", price: 1},
    {ingredient: "crushed tomatoes", price: 1},
    {ingredient: "apple pucker", price: 2},
    {ingredient: "sour mix", price: 2},
    {ingredient: "tomatoes", price: 1},
    {ingredient: "ground turkey", price: 2},
    {ingredient: "smoked paprika", price: 1},
    {ingredient: "onions", price: 1},
    {ingredient: "parmigiano reggiano", price: 2},
    {ingredient: "veal cutlets", price: 3},
    {ingredient: "dry white wine", price: 2},
    {ingredient: "capers", price: 1},
    {ingredient: "veggie burgers", price: 2},
    {ingredient: "lettuce", price: 1},
    {ingredient: "kaiser roll", price: 2},
    {ingredient: "tomato", price: 1},
    {ingredient: "blue cheese", price: 1},
    {ingredient: "skinless chicken thighs", price: 1},
    {ingredient: "minced ginger", price: 1},
    {ingredient: "curry paste", price: 1},
    {ingredient: "thai basil", price: 1},
    {ingredient: "honey maid graham pie crust", price: 1},
    {ingredient: "vanilla flavor instant pudding", price: 1},
    {ingredient: "persian cucumbers", price: 1},
    {ingredient: "macaroni", price: 1},
    {ingredient: "jack cheese", price: 1},
    {ingredient: "stewed tomatoes", price: 1},
    {ingredient: "sage", price: 1},
    {ingredient: "chilli flakes", price: 1},
    {ingredient: "rye bread", price: 1},
    {ingredient: "goat\ 's cheese", price: 2},
    {ingredient: "low-sodium soy sauce", price: 1},
    {ingredient: "crushed red pepper", price: 1},
    {ingredient: "beef short ribs", price: 3},
    {ingredient: "green cabbage", price: 1},
    {ingredient: "sesame oil", price: 1},
    {ingredient: "spaghetti", price: 1},
    {ingredient: "heirloom tomatoes", price: 1},
    {ingredient: "gorgonzola", price: 1},
    {ingredient: "chickpeas", price: 1},
    {ingredient: "bottom round", price: 3},
    {ingredient: "tomato soup", price: 2},
    {ingredient: "persian cucumbers", price: 1},
    {ingredient: "t-bone steaks", price: 4},
    {ingredient: "t-bone steak", price: 4},
    {ingredient: "steak sauce", price: 1},
    {ingredient: "green peppercorns", price: 1},
    {ingredient: "cracked pepper", price: 1},
    {ingredient: "ancho chile powder", price: 1},
    {ingredient: "evoo", price: 2},
    {ingredient: "red onions", price: 1},
    {ingredient: "balsamic vinegar", price: 1},
    {ingredient: "arborio rice", price: 1},
    {ingredient: "chicken stock", price: 1},
    {ingredient: "fresh sage", price: 1},
    {ingredient: "candy", price: 1},
    {ingredient: "nectarines", price: 1},
    {ingredient: "lemon balm", price: 1},
    {ingredient: "sea scallops", price: 4},
    {ingredient: "cilantro", price: 1},
    {ingredient: "panko breadcrumbs", price: 1},
    {ingredient: "ras-el-hanout", price: 2},
    {ingredient: "harissa", price: 2},
    {ingredient: "serrano chile", price: 1},
    {ingredient: "ground turmeric", price: 1},
    {ingredient: "naan", price: 1},
    {ingredient: "jalapeño pepper", price: 1},
    {ingredient: "corn tortillas", price: 1},
    {ingredient: "queso fresco", price: 1},
    {ingredient: "ears of corn", price: 1},
    {ingredient: "sunflower oil", price: 1},
    {ingredient: "pepitas", price: 2},
    {ingredient: "beet", price: 1},
    {ingredient: "swiss chard", price: 1},
    {ingredient: "kale", price: 1},
    {ingredient: "bread", price: 1},
    {ingredient: "vegan butter", price: 1},
    {ingredient: "nutmeg", price: 1},
    {ingredient: "coconut sugar", price: 2},
    {ingredient: "cardamom pod", price: 1},
    {ingredient: "ground nutmeg", price: 1},
    {ingredient: "halloumi cheese", price: 2},
    {ingredient: "endive", price: 1},
    {ingredient: "bosc pear", price: 1},
    {ingredient: "fennel", price: 1},
    {ingredient: "red chile", price: 1},
    {ingredient: "dried cherries", price: 1},
    {ingredient: "sherry vinegar", price: 2},
    {ingredient: "green beans", price: 1},
    {ingredient: "corn kernels", price: 1},
    {ingredient: "persian peas", price: 1},
    {ingredient: "lima beans", price: 1},
    {ingredient: "potato", price: 1},
    {ingredient: "prunes", price: 1},
    {ingredient: "green peas", price: 1},
    {ingredient: "ale", price: 2},
    {ingredient: "white cheddar", price: 1},
    {ingredient: "pimento", price: 1},
    {ingredient: "basil", price: 1},
    {ingredient: "octopus", price: 4},
    {ingredient: "cuttlefish", price: 4},
    {ingredient: "mussels", price: 2},
    {ingredient: "green garlic", price: 1},
    {ingredient: "white wine", price: 3},
    {ingredient: "dried sage", price: 1},
    {ingredient: "dried mint", price: 1},
    {ingredient: "dried thyme", price: 1},
    {ingredient: "white onions", price: 1},
    {ingredient: "passionfruit", price: 1},
    {ingredient: "mangoes", price: 1},
    {ingredient: "prosecco", price: 2},
    {ingredient: "milk chocolate", price: 1},
    {ingredient: "pistachios", price: 1},
    {ingredient: "avocados", price: 1},
    {ingredient: "limes", price: 1},
    {ingredient: "serrano chiles", price: 1},
    {ingredient: "brown rock sugar", price: 2},
    {ingredient: "grappa", price: 5},
    {ingredient: "salmon", price: 3},
    {ingredient: "new potatoes", price: 1},
    {ingredient: "bay leaf", price: 1},
    {ingredient: "baby carrots", price: 1},
    {ingredient: "cauliflower", price: 1},
    {ingredient: "broccoli", price: 1},
    {ingredient: "baby zucchini", price: 1},
    {ingredient: "beets", price: 1},
    {ingredient: "chantilly cream", price: 2},
    {ingredient: "strawberry", price: 1},
    {ingredient: "meringue", price: 2},
    {ingredient: "old bay seasoning", price: 1},
    {ingredient: "herb", price: 1},
    {ingredient: "mayo", price: 1},
    {ingredient: "tabasco", price: 1},
    {ingredient: "cream sherry", price: 2},
    {ingredient: "chipotle chiles in adobo", price: 1},
    {ingredient: "agave syrup", price: 2},
    {ingredient: "rice", price: 1},
    {ingredient: "tomato purée", price: 1},
    {ingredient: "stock", price: 1},
    {ingredient: "ramps", price: 3},
    {ingredient: "miso", price: 1},
    {ingredient: "seasoned rice vinegar", price: 1},
    {ingredient: "greek yogurt", price: 1},
    {ingredient: "yogurt", price: 1},
    {ingredient: "can chickpeas", price: 1},
    {ingredient: "cod", price: 2},
    {ingredient: "chive", price: 1},
    {ingredient: "dill", price: 1},
    {ingredient: "condensed tomato soup", price: 1},
    {ingredient: "cooked chicken", price: 2},
    {ingredient: "brown rice", price: 1},
    {ingredient: "vegetable stock", price: 1},
    {ingredient: "chile flakes", price: 1},
    {ingredient: "noodle", price: 1},
    {ingredient: "farmers cheese", price: 2},
    {ingredient: "sprinkle", price: 1},
    {ingredient: "oyster sauce", price: 1},
    {ingredient: "white sugar", price: 1},
    {ingredient: "graham crackers", price: 1},
    {ingredient: "confectioner's sugar", price: 1},
    {ingredient: "filo dough", price: 2},
    {ingredient: "togarashi", price: 2},
    {ingredient: "firm tofu", price: 1},
    {ingredient: "scallion", price: 1},
    {ingredient: "chipotle peppers in adobo", price: 1},

]
